name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches:
      - main
  schedule:
    - cron: "41 7 * * 3"
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Run Scorecard
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa
        with:
          sarif_file: scorecard.sarif
